Refactor LocalUploadStrategy, Replace Constants Class, and Implement DocumentBuilder
zarhell/cgpCore pull request #1
Opened 2023-06-06 23:03 UTC by zarhell

- Refactored the LocalUploadStrategy class to improve readability and maintainability. The code has been organized into methods with clear responsibilities, and logging messages have been added to provide better visibility into the execution flow.
- Replaced the Constants class with an Enum class, providing a more structured and type-safe approach to defining constants.
- Implemented a DocumentBuilder class to handle multiple parameters for document creation (still needs implementation)
-Document the use case with JavaDoc for all classes
-Defined Logs for all Components
* [Related Ticket Req2Act:](https://sumptuous-spandex-1e9.notion.site/Req2-File-Upload-and-Download-276413fe6406406cbee6386ad47ae069?pvs=4)

2023-06-07 19:55 UTC, nordonezc requested changes
Review comments and check some items to discuss in the meeting.

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/commons/service/GcpCredentialsService.java
> +    private static final String GCP_KEY_JSON  = String.format("src%smain%sresources%sgcp-key.json", File.separator, File.separator, File.separator);
Well use of file separator, thats helps to work for different OS, now, it seems difficult to read. Consider StringJoiner

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/search/config/SearchStrategyConfig.java
> +        if (fetchStrategy.equals(EnumConstansCore.LOCAL.getValue())) {
What does that mean 'Core' it is a well defined name? 
On the other hand, check cases when constants should be defined in enums or in utility class. Discuss it in the meeting.

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/upload/config/UploadStrategyConfig.java
> +        if (uploadStrategy.equals(EnumConstansCore.LOCAL.getValue())) {
Considering that I have seen LOCAL value in so many places, this reinforces the idea of creating a utility class with static final string constants that can be imported statically

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/upload/service/LocalUploadStrategy.java
> +                .orElse(new CoreSavedDocument());
Nice!

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/upload/service/LocalUploadStrategy.java
> +            logger.info("LocalUploadStrategy | uploadFilesRS | File successfully written to disk");
do you think this log really helps? how can we know at which level has failed in case of?

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/upload/service/LocalUploadStrategy.java
> +        documentToProcess.getDocumentalDates().setDocumentCreationDetails(LocalDateTime.now());
Check on meeting to refactor it

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/commons/domain/DocumentAreaDto.java
> +public class DocumentAreaDto   {
What are the implications of not implementing serializable? Discuss it at meeting

2023-06-07 19:55 UTC, nordonezc commented on src/main/java/com/mintic/proyecto/core/commons/constans/ConstansCore.java
> -
final class is not bad idea for constant, but remember to create private constructor to reinforce idea that is an utility class.

2023-06-08 15:49 UTC, zarhell commented on src/main/java/com/mintic/proyecto/core/commons/constans/ConstansCore.java
> -
This ConstansCore was replaced for EnumConstansCore instead

2023-06-13 12:47 UTC, nordonezc approved these changes
Nice! Good job documenting and refactoring classes

2023-06-13 19:44 UTC, merged